/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { IsAdmin } from "./IsAdmin";
import { IsAdminCountArgs } from "./IsAdminCountArgs";
import { IsAdminFindManyArgs } from "./IsAdminFindManyArgs";
import { IsAdminFindUniqueArgs } from "./IsAdminFindUniqueArgs";
import { CreateIsAdminArgs } from "./CreateIsAdminArgs";
import { UpdateIsAdminArgs } from "./UpdateIsAdminArgs";
import { DeleteIsAdminArgs } from "./DeleteIsAdminArgs";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { Product } from "../../product/base/Product";
import { Review } from "../../review/base/Review";
import { IsAdminService } from "../isAdmin.service";
@graphql.Resolver(() => IsAdmin)
export class IsAdminResolverBase {
  constructor(protected readonly service: IsAdminService) {}

  async _isAdminsMeta(
    @graphql.Args() args: IsAdminCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [IsAdmin])
  async isAdmins(
    @graphql.Args() args: IsAdminFindManyArgs
  ): Promise<IsAdmin[]> {
    return this.service.isAdmins(args);
  }

  @graphql.Query(() => IsAdmin, { nullable: true })
  async isAdmin(
    @graphql.Args() args: IsAdminFindUniqueArgs
  ): Promise<IsAdmin | null> {
    const result = await this.service.isAdmin(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => IsAdmin)
  async createIsAdmin(
    @graphql.Args() args: CreateIsAdminArgs
  ): Promise<IsAdmin> {
    return await this.service.createIsAdmin({
      ...args,
      data: {
        ...args.data,

        orders: args.data.orders
          ? {
              connect: args.data.orders,
            }
          : undefined,

        product: args.data.product
          ? {
              connect: args.data.product,
            }
          : undefined,

        reviews: args.data.reviews
          ? {
              connect: args.data.reviews,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => IsAdmin)
  async updateIsAdmin(
    @graphql.Args() args: UpdateIsAdminArgs
  ): Promise<IsAdmin | null> {
    try {
      return await this.service.updateIsAdmin({
        ...args,
        data: {
          ...args.data,

          orders: args.data.orders
            ? {
                connect: args.data.orders,
              }
            : undefined,

          product: args.data.product
            ? {
                connect: args.data.product,
              }
            : undefined,

          reviews: args.data.reviews
            ? {
                connect: args.data.reviews,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => IsAdmin)
  async deleteIsAdmin(
    @graphql.Args() args: DeleteIsAdminArgs
  ): Promise<IsAdmin | null> {
    try {
      return await this.service.deleteIsAdmin(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Order], { name: "products" })
  async findProducts(
    @graphql.Parent() parent: IsAdmin,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findProducts(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Order, {
    nullable: true,
    name: "orders",
  })
  async getOrders(@graphql.Parent() parent: IsAdmin): Promise<Order | null> {
    const result = await this.service.getOrders(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Product, {
    nullable: true,
    name: "product",
  })
  async getProduct(@graphql.Parent() parent: IsAdmin): Promise<Product | null> {
    const result = await this.service.getProduct(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Review, {
    nullable: true,
    name: "reviews",
  })
  async getReviews(@graphql.Parent() parent: IsAdmin): Promise<Review | null> {
    const result = await this.service.getReviews(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
